### ISSUE TITLE
[Info] I've Added Your Work to the Arch User Repository

### ISSUE THREAD

**Issue by dhtseany** [grigio/obs-cmd#10]
Hey there, I like your work and I found it while searching for a replacement for obs-cli. I've added it to the AUR and it can be found here:

https://aur.archlinux.org/packages/obs-cmd

I'll watch here for major version updates and update the AUR accordingly. Thanks for your efforts!

**Comment by grigio** [comment]
As a Archlinux user I appreciate :+1: 

If you want, you add a PR in the readme on how to install it in Archlinux, I installed it with `yay -Sy obs-cmd` and it works fine

**Comment by dhtseany** [comment]
https://github.com/grigio/obs-cmd/pull/13/commits
