### ISSUE TITLE
[Request] Add command option to input Websocket Password

### ISSUE THREAD

**Issue by dhtseany** [grigio/obs-cmd#11]
Hey there! I'd like to recommend adding a command option for specifying the websocket password to eliminate the need for the `~/.config/obs-cmd.toml` config file. My previous scripts, based on `obs-cli`, already specified this info using my own global config file and it'd be nice if I could continue this trend as I have 5 live streaming rigs with their own unique configs. Thanks!

**Comment by grigio** [comment]
Fixed in https://github.com/grigio/obs-cmd/releases/tag/v0.16.1
