### ISSUE TITLE
Unclear on where to add websockets password

### ISSUE THREAD

**Issue by salt86** [grigio/obs-cmd#16]
I had to do a reinstall of my OS. I'm trying to remember where to input the websockets password.

I know it's a file named obs-cmd.toml and its contents are:

`OBS_WS_PASSWORD="trCYeMhv9k50e01s"`

but i don't know where to leave the file. So far I've tried in the home folder and ~/.config

typing in the password in terminal allows for a connection, but otherwise I'm getting a handshake error.

**Comment by grigio** [comment]
Now it doesn't use the toml file anymore

you can use it like this

```
obs-cmd --websocket obsws://localhost:4455/yourpassword info
```

but if your password is `secret` it is implicit so you can do

```
obs-cmd info
```

**Comment by salt86** [comment]
I see. I'll just change my password.

Thanks

**Comment by grigio** [comment]
Maybe in future I'll add the configuration file, but for now i close it
