### ISSUE TITLE
How minimal are you wanting the project to be?

### ISSUE THREAD

**Issue by AethanFoot** [grigio/obs-cmd#21]
I find this project amazing and saves me implementing a basic interface in python, and adding to this is easy as I'm very familiar with rust. I ask this as would plan on adding extra bits as time goes on (and I have time), and wonder how much I should open PRs for (I would probably mainly add other Requests stuff and helpers around them).

Amazing work!!

**Comment by grigio** [comment]
I started this project as a `obs-cli` replacement with obswebsocket v5 support, with "minimal" I mean that I just implemented the API i needed. You are welcome to propose a PR if it doesn't break the code and it implements other API methods or general useful features
