### ISSUE TITLE
Adding Source Selection

### ISSUE THREAD

**Issue by RileyMeta** [grigio/obs-cmd#22]
Any thoughts on adding Scenes so the end-user can enable/disable them like how you can mute Audio Sources?

**Comment by mansman12** [comment]
Can you clarify what you mean? The title says source selection but your comment says scenes?

**Comment by RileyMeta** [comment]
Yeah, that's my bad, lol. **SOURCES**
Any plan to add sources to the selections so users could toggle visibility? 

Ex: `obs-cmd source "webcam" toggle-visibility`

**Comment by mansman12** [comment]
I've done that on my fork: https://github.com/mansman12/obs-cmd

If you're able to build it, the usage is `obs-cmd scene-item toggle <scene> <source>`.

My fork also has collection switching added.

**Comment by RileyMeta** [comment]
Exactly what I needed, you're awesome ❤️
