### ISSUE TITLE
Awesome Project

### ISSUE THREAD

**Issue by tbocek** [grigio/obs-cmd#33]
Hi, 

Great project! I had the same issue last year with websockets v5, so I quickly hacked together this: https://github.com/tbocek/obs-cli5x. Since your project does what I need, and it seems well maintained, I'm going to switch to use your version. 

There is even an aur version, which makes my life easier. Awesome!

Thomas 
(this is not an issue, so you can close it, just wanted to say thanks)

**Comment by grigio** [comment]
Good to know, welcome
