### ISSUE TITLE
Request: allow reading websocket secret from a text file.

### ISSUE THREAD

**Issue by Da-Boom** [grigio/obs-cmd#52]
I post my OBS websocket bash scripts to my codeburg. I want to be able to read the websocket secret from a file outside the repository so i dont have to include it. with possible options for plain text or hashed/salted - however, plain text is a fine start right now though -- i mean, obs-websocket stores password in plain text currently as well, as bad a security practice as that is.

hey wait! maybe we could read it direct from there if possible. or at least add the option to read direct from the OBS config.

**Comment by grigio** [comment]
i don't want to make it overengineered, what do you think to grab the secret from an ENV variable ?

**Comment by jjafuller** [comment]
Reading from ENV var sounds like a good idea to me.
