### ISSUE TITLE
version 'GLIBC_2.29' not found (required by obs-cmd) error

### ISSUE THREAD

**Issue by AndyReifman** [grigio/obs-cmd#56]
I'm hitting the above error when trying to run `obs-cmd` on a Linux box running Ubuntu 18.04.

I downloaded this release: https://github.com/grigio/obs-cmd/releases/tag/v0.17.6

and ran `chmod +x obs-cmd-linux-amd64 && sudo mv obs-cmd-linux-amd64 /usr/local/bin/obs-cmd` as instructed.

**Comment by dhtseany** [comment]
Verify you have libc6 installed:
https://packages.debian.org/buster/amd64/libc6/download

sudo apt-get install libc6
...should get it done.

**Comment by kostadinsh** [comment]
My guess is that the binary was built against a newer Ubuntu version - meaning newer glibc too, so you are probably out of luck, unless you find out how to update your glibc version, which is probably a really bad idea. I'd suggest updating to a newer Ubuntu release.

**Comment by grigio** [comment]
the version on glibc supported is the one provided by `ubuntu-latest` lts
