### ISSUE TITLE
Error: Connect(Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))

### ISSUE THREAD

**Issue by alsavage** [grigio/obs-cmd#61]
$ obs-cmd recording start
Error: Connect(Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))

$ obs-cmd --version
obs-cmd 0.17.8

Ubuntu 24.04
OBS 30.2.3 (64 bit), installed from repo

**Comment by DigitalDragon64** [comment]
Same problem here with Arch Linux with obs-cmd version 0.17.8 installed from AUR. I'm using sway as wayland compositor if this is important.

**Comment by dhtseany** [comment]
Hi, the current AUR version is 0.17.9. Does updating with a cleanbuild help at all?

**Comment by DigitalDragon64** [comment]
Found the problem. obs-studio (30.2.1-1) on Arch Linux isn't build with obs-websocket. I had to manually compile obs, to use the websocket feature. After I launched the manually compiled obs (and configure the websocket server), obs-cmd started to work :)

**Comment by grigio** [comment]
Another option is using OBS from Flatpak, it has the support

_Originally posted by @DigitalDragon64 in https://github.com/grigio/obs-cmd/issues/61#issuecomment-2442593143_

**Comment by nozwock** [comment]
I encountered this as well :(

Moved to the Flathub build.
