### ISSUE TITLE
[Suggestion] Add help command.

### ISSUE THREAD

**Issue by AdiHarif** [grigio/obs-cmd#7]
Willing to contribute in case help is needed\wanted :)

**Comment by grigio** [comment]
i don't know, is there a way to generate it automatically from the implemented options ? the syntax is the same of the official obs api

**Comment by AdiHarif** [comment]
Probably not completely automatically, however there must be a Rust crate to help with that.
Usage of this package is indeed pretty straight-forward, still this --help flag is the first thing i do when i install a new cli tool.

**Comment by grigio** [comment]
Fixed in https://github.com/grigio/obs-cmd/releases/tag/v0.16.1
